name: fuelcredit-laravel-cd

env:
  "S3_BUCKET_NAME": "fuelcredit-laravel-bucket"
  "EBS_APPLICATION_NAME": "fuelcredit-laravel-prod"
  "EBS_ENVIRONMENT_NAME": "Fuelcreditlaravelprod-env"
  "AWS_REGION": "eu-central-1"
  "DEPLOY_PACKAGE_NAME": "laravel-app-${{github.sha}}.zip"
  
on:
  push:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.0'
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit
#   build:
#     needs: test
#     runs-on: ubuntu-latest

#     steps:
#       - name: Clone the repository
#         uses: actions/checkout@v3

#       - name: Zip the repository
#         run: zip -r ${{env.DEPLOY_PACKAGE_NAME}} ./ -x *.git*
      
#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           node-version: 16
#           aws-access-key-id: ${{secrets.ACCESS_KEY_ID}}
#           aws-secret-access-key: ${{secrets.SECRET_ACCESS_KEY}}
#           aws-region: ${{env.AWS_REGION}}
          
#       - name: Upload Deployment to S3 Bucket
#         run: aws s3 cp ${{env.DEPLOY_PACKAGE_NAME}} s3://${{env.S3_BUCKET_NAME}}/
      
#       - name: Create new Elastic Beanstalk Application Version
#         run: |
#           aws elasticbeanstalk create-application-version \
#           --application-name ${{env.EBS_APPLICATION_NAME}} \
#           --source-bundle S3Bucket="${{env.S3_BUCKET_NAME}}",S3Key="${{env.DEPLOY_PACKAGE_NAME}}" \
#           --version-label "ver-${{ github.sha }}" \
#           --description "commit-sha-${{ github.sha }}"
        
#       - name: Deploy new ElasticBeanstalk Application Version
#         run: aws elasticbeanstalk update-environment --environment-name ${{env.EBS_ENVIRONMENT_NAME}} --version-label "ver-${{ github.sha }}"
      
#       - name: Print Success Message on Completion
#         run: echo "CI/CD pipeline ran successfully"
